export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_FAIL  =  "PRODUCT_FAIL";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS"
export const ADD_CART_SUCCESS=  "ADD_CART_SUCCESS"
export const TOTAL_PRICE_UPDATE = "TOTAL_PRICE"



export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_PROFILE = "LOGIN_PROFILE";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS =  "LOGOUT_SUCCESS"