export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_FAIL  =  "PRODUCT_FAIL";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS"
export const ADD_CART_SUCCESS=  "ADD_CART_SUCCESS"
export const TOTAL_PRICE_UPDATE = "TOTAL_PRICE"